### ISSUE TITLE
Sample with images?

### ISSUE THREAD

**Issue by melMass** [jorge-brito/svelte-masonry-layout#1]
Hi,

I was planning on implementing masonry in svelte myself and discovered this repo but cannot find how to make it work, I extracted the relevant parts in a REPL if you don't mind having a look. [Testing svelte-masonry-layout REPL](https://svelte.dev/repl/408b3282047f44d1b9d78bdcfec5daeb?version=3.47.0)

Thanks

**Comment by melMass** [comment]
![image](https://user-images.githubusercontent.com/7041726/163272235-c70c2d29-f111-44a1-9255-0df52ba5c219.png)

**Comment by jorge-brito** [comment]
Hello!

The problem is that in order to compute the desired position of each element within the grid, each item must have a pre-defined height.

I made some changes to your code in the REPL, you can see the result [here](https://svelte.dev/repl/5a9b9f3155154c61926524e2ec820467?version=3.47.0).

I noticed that in your `randomImage()` function you weren't using the random `size`, instead you were only returning the `src` of each image. I changed the code so that the return is an object `{ src, size }` where the size is the dimensions of the image.

```svelte
const randomImage = (index) => {
  const size = randomSize();
  const src = `https://picsum.photos/seed/${index+seed}/${size.x}/${size.y}`;
  // each item has a size and a src
  return { size, src }
}
```

We need to know the `height` of each item in the grid, however the `width` will be computed automatically (since every item will have the same width, but with different height).

In the `Image.svelte` component, i declared the `size` propertie. Instead of assigning the `height` prop once the image is loaded, we take the height passed by the component with the `size` property.

```svelte
$: height = size.y; 
```

We then set the height of the `.container` element using the `height`:

```svelte
<div class="container" style:height="{height}px">
  <img bind:this={elm} {src} {alt} />	
  <span>
    <strong>size</strong>: {width}x{height}px
  </span>
</div>
```

I used a `<span>` element  just to group the text that shows the dimensions of each image. Then i applied some CSS to let the `<img>` with `width: 100%` and `height: 100%`, and `position: absolute` for the `<span>` element with the text and positioned at the bottom-left of each item.

```css
.container {
  position: relative;
  overflow: hidden;
}

img {
  width: 100%;
  height: 100%;
}

span {
  position: absolute;
  bottom: 0;
  left: 0;

  padding: 0.75rem;
  background: #eee;
  width: 100%;

  /* the  text will be hidden by default */
  opacity: 0;
  transition: opacity 0.3s ease;
}

/* the  text will appear once the user hovers the mouse within the item */
.container:hover span {
  opacity: 1;
}
```
